config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # commentは一人のユーザーが複数投稿できるため複数系『resources』
  end
  resources :homes, path: 'home', except: [:index, :create, :new, :edit, :show, :update, :destroy] do
    collection do
      get 'about'
    end
  end
  resources :users, only: [:index, :edit, :show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user) # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べるメソッドを定義
    favorites.where(user_id: user_id).exists? # モデル名.where(任意のカラム名: 格納されている値) user_idカラムの全レコードを検索し、user.idが含まれているか確認
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!,except: [:top, :about] # ログインしていないユーザーがアクセスできるのはtopとaboutのみ
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後はマイページ（現在ログインしているユーザーのページに
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end
  
  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  protected # ストロングパラメータ（他のコントローラも参照可）

  def configure_permitted_parameters # sign up,sign in画面で追加したnameデータの操作許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email]) # emailも必要
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id]) # ビューに渡すからインスタンス変数に
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    if @book_comment.save
      redirect_to book_path(@book)
    else
      render 'books/show'
    end
  end
  
  def destroy
    @comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @comment.destroy
    redirect_to book_path(params[:book_id])
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only:[:edit] # 編集画面へのアクセス制限
  
  def create
    @book = Book.new(book_params) # 投稿データを取得
    @book.user_id = current_user.id # Bookモデルのuser_idカラムに現在ログインしているユーザーのidを取得
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book) # 投稿詳細ページにリダイレクト
    else
      @books = Book.all # 投稿一覧を表示
      @user = current_user # 部分テンプレートのマイページを表示するため
      render :index
    end
  end
  
  def index
    @book = Book.new # 投稿フォーム用に空のインスタンスを渡す
    @books = Book.all
    @user = current_user # 部分テンプレートのマイページを表示するため,投稿一覧はログインユーザー情報しか表示しない
  end

  def show
    @book_new = Book.new # 投稿フォーム用に空のインスタンスを渡す
    # ↑@bookにすると、その後find(params[:id])で値が取得されてしまいform_withがupdateになるためインスタンス名を値を取得するものとは別にする
    @book = Book.find(params[:id])
    @book_comment = BookComment.new # コメント投稿用のインスタンス作成
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path #投稿一覧ページにリダイレクト
  end
  
  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user #投稿したユーザーと現在ログインしているユーザーを比較するメソッド
    @book = Book.find(params[:id]) #投稿を取得
    unless @book.user == current_user #投稿したユーザーが現在ログインしているユーザーではない場合
      redirect_to books_path #投稿一覧画面にリダイレクト
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id]) # パラメータ(book_id)で指定された投稿(bookテーブル)を検索して、変数に格納
    favorite = current_user.favorites.new(book_id: book.id) # favorite = Favorite.new(book_id: book.id) \ current_user_id = current_user.idと同じ
    # favorite = Favorite.new(book_id: book.id) # 上で取得した投稿IDをbook_idカラムに格納し、favoriteインスタンスに渡す
    # current_user_id = current_user.id # 『いいね』したユーザー（ログインユーザー）のIDを取得
    favorite.save
    redirect_back fallback_location: @book # 直前の画面にリダイレクト
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id) # 生成したfavoriteモデルのインスタンスのuser_idカラムにcurrent_user（ログインユーザー）を、book_idカラムに上で取得した投稿IDを格納
    favorite.destroy
    redirect_back fallback_location: @book
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit] # 編集画面へのアクセス制限
  
  def index
    @user = current_user # 部分テンプレートのマイページを表示するため,ユーザー一覧はログインユーザー情報しか表示しない
    @book = Book.new # フォーム用の空モデルを生成し、form_withを経て、books_controllerのcreateアクションに渡す
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id]) # ユーザーのデータを1件取得
    @books = @user.books # 上の@userで取得したユーザーに関連する投稿データを取得する
    @book = Book.new # フォーム用の空モデルを生成し、form_withを経て、books_controllerのcreateアクションに渡す
  end
  
  def edit
    @user = User.find(params[:id]) 
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id) # ユーザー詳細ページにリダイレクト
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def correct_user #プロフィールのユーザーと現在ログインしているユーザーが一致しているか比較するメソッド
    @user = User.find(params[:id]) #ユーザーIDを取得
    unless @user == current_user #プロフィールのユーザーと現在ログインしているユーザーが異なる場合
      redirect_to user_path(current_user) #自分のプロフィール詳細へリダイレクト
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <div class = "error_explanation"><!-- エラー内容はclassで囲っておく -->
            <h3><%=pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3><!-- pluralizeメソッドでエラーの数を複数形かどうか判断する -->
            <ul><!-- エラーメッセージをリストとして表示する -->
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form_with model:@book, local:true do |f| %>
          <div class = "form-group">
            <label for = "book_title">Title</label>
            <%= f.text_field :title, class: "form-control", id: "book_title" %>
          </div>
          <div class = "form-group">
            <label for = "book_body">Opinion</label>
            <%= f.text_area :body, class: "form-control", id: "book_body" %>
          </div>
          <div class = "form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container px-sm-0">
    <!-- 部分テンプレートでここにrowがある-->
      <%= render 'users/form', user: @user, book: @book %>
      <div class = "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class = "table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %> <!-- その投稿に関連したユーザーのページに遷移 -->
                  <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %> <!-- 投稿に付けられた『いいね』に自分（ログインユーザー）が含まれているか -->
                <p> <!-- 含まれている場合 -->
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    ♥<%= book.favorites.count %> いいね
                  <% end %>
                </p>
                <% else %>
                <p> <!-- 含まれていない場合 -->
                  <%= link_to book_favorites_path(book), method: :post do %>
                    ♡<%= book.favorites.count %> いいね
                  <% end %>
                </p>
                <% end %>
              </td>
              <td><p>コメント件数：<%= book.book_comments.count %></p></td>
            </tr>
          　<% end %>
          </tbody>
        </table>
      </div>
    </div><!-- rowのdiv -->
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container">
      <%= render 'users/form', user: @book.user, book: @book_new %>
      <div class = "col-md-8 offset-md-1">
        <% if @book_comment.errors.any? %> <!-- エラーメッセージ表示させるにはインスタンス必要(new) -->
        <div id="error_explanation">
          <h3><%= pluralize(@book_comment.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <h2>Book detail</h2>
        <table class = "table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %><!-- 投稿したユーザーの詳細ページへ -->
                  <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                  <%= @book.user.name %><!-- 投稿者名 -->
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td><%= @book.body %></td>
              <td>
                <% if @book.favorited_by?(current_user) %> <!-- 投稿に付けられた『いいね』に自分（ログインユーザー）が含まれているか -->
                <p> <!-- 含まれている場合 -->
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    ♥<%= @book.favorites.count %> いいね
                  <% end %>
                </p>
                <% else %>
                <p> <!-- 含まれていない場合 -->
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    ♡<%= @book.favorites.count %> いいね
                  <% end %>
                </p>
                <% end %>
              </td>
              <td>
                <p>コメント件数：<%= @book.book_comments.count %></p>
              </td>
              <% if @book.user == current_user %><!-- もし、投稿者 == 現在ログインしているユーザ だったら -->
                <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <!-- コメント機能 -->
        <div class="comments mb-3">
        <% @book.book_comments.each do |book_comment| %>
          <%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
          <%= book_comment.user.name %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
          <span class="comment-delete">
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete %> <!-- 引数の順番に注意book/bookのid/comment/commentのid -->
          </span>
          <% end %><br>
        <% end %>
        </div>
        <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5', class: "form-control mb-3" ,placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
        </div> 
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container">
    <div class = "row">
      <h1 class = "px-3 mx-auto">
        Welcome to
        <i class = "fas fa-book"></i><strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p class = "notice"><%= notice %></p>
  <div class = "container">
    <div class = "row">
      <div class = "mx-auto col-xl-6">
        <h1>
          welcome to
          <i class = "fas fa-book"></i><strong>Bookers</strong>
          !!
        </h1>
        <p>
          In
          <i class = "fas fa-book"></i><strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class = "btn-wrapper col-10 mx-auto"> <!-- btn-wrapperはボタンを囲っているから付けただけで意味はない -->
          <div class = "row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
          </div>
          <div class = "row">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2R</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark"> <!-- .navbar-navクラスのflex-directionはデフォルトでcolumnになっているので、縦並びになる。PCレイアウトの時に横並びにするにはnavに"navbar-expand-xxを指定。" -->
        <div class = "container">
          
          <%= link_to root_path, class: "navbar-brand" do %>
            <span>Bookers</span>
          <% end %>
          
          <ul class = "navbar-nav ml-auto">
            <% if user_signed_in? %><!-- ログイン後 -->
              <li>
                <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %> <!-- 現在ログインしているユーザー（マイページ）へのリンク -->
              </li>
              <li>
                <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
              </li>
            
            <% else %><!-- ログイン前 -->
              <li>
                <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li>
                <%= link_to " About", about_homes_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
    <% if @book.errors.any? %>
      <div class = "error_explanation"><!-- エラー内容はclassで囲っておく -->
        <h3><%=pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h3><!-- pluralizeメソッドでエラーの数を複数形かどうか判断する -->
        <ul><!-- エラーメッセージをリストとして表示する -->
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class = "row">
      <div class = "col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
        <table class = "table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class = "row">
          <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        
        <h2 class = "mt-3">New book</h2>
        <%= form_with model:book, local:true do |f| %>
          <div class = "form-group">
            <label for = "book_title">Title</label>
            <%= f.text_field :title, class: "form-control", id: "book_title" %>
          </div>
          <div class = "form-group">
            <label for = "book_body">Opinion</label>
            <%= f.text_area :body, class: "form-control", id: "book_body" %>
          </div>
          <div class = "form-group">
            <%= f.submit 'Create Book', class: "btn btn-success" %>
          </div>
        <% end %>
      </div>

app/views/users/edit.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-5 px-sm-0 mx-auto">
        <h2>User info</h2>
          <% if @user.errors.any? %>
          <div class = "error_explanation"><!-- エラー内容はclassで囲っておく -->
            <h3><%=pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3><!-- pluralizeメソッドでエラーの数を複数形かどうか判断する -->
            <ul><!-- エラーメッセージをリストとして表示する -->
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form_with model:@user, local:true do |f| %>
          <div class = "form-group">
            <label for = "user_name">Name</label>
            <%= f.text_field :name, class: "form-control", id: "user_name" %>
          </div>
          <div class = "form-group">
            <label for = "user_image">Image</label>
            <%= f.attachment_field :profile_image, class: "form-control-file", id: "user_image" %>
          </div>
          <div class = "form-group">
            <label for = "user_introduction">Introduction</label>
            <%= f.text_area :introduction, class: "form-control", id: "user_introduction" %>
          </div>
          <div class = "form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container px-sm-0">
    <!-- 部分テンプレートでここにrowがある-->
      <%= render 'users/form', user: @user, book: @book %>
      <div class = "col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class = "table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div><!-- rowのdiv -->
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id = "notice"><%= notice %></p>
  <div class = "container px-sm-0">
    <!-- 部分テンプレートでここにrowがある-->
      <%= render 'users/form', user: @user, book: @book %>
      <div class = "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class = "table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td><p>コメント件数：<%= book.book_comments.count %></p></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div><!-- rowのdiv -->
  </div>
</main>